name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.3
          - 26.3
          - 27.2
          - 28.2
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: cask/setup-cask@master
        with:
          version: "snapshot"
      - uses: actions/checkout@v3
      - run: cask install
      - name: Run tests
        run: |
          emacs --version
          make test
