name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 25.3
          - 26.3
          - 27.2
          - 28.2
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install eldev
        run: |
          curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh
      - uses: actions/checkout@v3
      - run: |
          eldev prepare
      - name: Run tests
        run: |
          emacs --version
          make test
